# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: solo-in-drops-1.0dev
channels:
  - conda-forge
  - bioconda
  - Freenome
  - defaults
  
dependencies:
  - conda-forge::python=3.7.3
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  - conda-forge::graphviz=2.42.3
  - bioconda::fastqc=0.11.8
  - bioconda::multiqc=1.7
  - bioconda::star=2.7.6a
  - bioconda::samtools=1.11
  - bioconda::seqkit=0.13.2
  - bioconda::bbmap=38.87
  - Freenome::bcl2fastq=2.20
